using FactionAPI.Services.Api.V0.Models;
using FactionAPI.Services.Infrastructure;
using FactionAPI.Services.Infrastructure.Models;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Routing;
using Microsoft.EntityFrameworkCore;
using Supporter = FactionAPI.Services.Infrastructure.Models.Supporter;

namespace FactionAPI.Services.Api.V0;

internal static class Endpoints
{
    public static void MapV0Endpoints(this IEndpointRouteBuilder endpoints)
    {
        var v0 = endpoints.MapGroup("v0");

        v0.MapGroup("supporter")
            .WithTags("Supporter")
            .MapGet("list", List);
        
        v0.MapGroup("telemetry")
            .WithTags("Telemetry")
            .MapGet("basic", Telemetry);
    }

    private static async Task<Results<Ok<SupporterFile>,BadRequest>> List([FromServices] FactionContext context)
    {
        IQueryable<Supporter> query = context.Supporters;
        
        var supporters = await query.Include(supporter => supporter.FactionId).ToListAsync();

        var result = new SupporterFile
        {
            Comment = "This file is automatically generated by the FactionAPI.Services.Api project.",
            Vampires = supporters.Where(x => x.FactionId.Equals("vampirism:vampire")).Select(Mapper.MapSupporter)
                .ToList(),
            Hunters = supporters.Where(x => x.FactionId.Equals("hunter")).Select(Mapper.MapSupporter).ToList(),
        };
        return TypedResults.Ok(result);
    }

    private static async Task<Ok> Telemetry(
        [FromServices] FactionContext context,
        [FromQuery(Name = "current")] string? modVersion = null,
        [FromQuery(Name = "mc")] string? mcVersion = null,
        [FromQuery(Name = "count")] int? modCount = null,
        [FromQuery(Name = "side")] string? side = null
        )
    {
        try
        {
            context.TelemetryEntries.Add(new TelemetryEntry
            {
                Timestamp = DateTime.UtcNow,
                Side = side,
                MinecraftVersion = mcVersion,
                ModVersion = modVersion,
                ModCount = modCount,
                ModId = "vampirism"
            });
            await context.SaveChangesAsync();
        }
        catch
        {
            // ignored
        }

        return TypedResults.Ok();
    }
}