// <auto-generated />
using System;
using FactionAPI.Services.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FactionAPI.Services.Infrastructure.Migrations
{
    [DbContext(typeof(FactionContext))]
    partial class FactionContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FactionAPI.Services.Core.Models.ConfigValue", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Key");

                    b.ToTable("ConfigValues");
                });

            modelBuilder.Entity("FactionAPI.Services.Core.Models.Supporter", b =>
                {
                    b.Property<string>("PlayerId")
                        .HasColumnType("text");

                    b.Property<string>("BookId")
                        .HasColumnType("text");

                    b.Property<string>("FactionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int?>("Type")
                        .HasColumnType("integer");

                    b.HasKey("PlayerId");

                    b.ToTable("Supporters");
                });

            modelBuilder.Entity("FactionAPI.Services.Core.Models.SupporterAppearance", b =>
                {
                    b.Property<string>("PlayerId")
                        .HasColumnType("text");

                    b.Property<string>("Key")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PlayerId", "Key");

                    b.ToTable("SupporterAppearance");
                });

            modelBuilder.Entity("FactionAPI.Services.Core.Models.TelemetryEntry", b =>
                {
                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MinecraftVersion")
                        .HasColumnType("text");

                    b.Property<int?>("ModCount")
                        .HasColumnType("integer");

                    b.Property<string>("ModVersion")
                        .HasColumnType("text");

                    b.Property<string>("Side")
                        .HasColumnType("text");

                    b.HasKey("Timestamp");

                    b.ToTable("TelemetryEntries");
                });

            modelBuilder.Entity("FactionAPI.Services.Core.Models.SupporterAppearance", b =>
                {
                    b.HasOne("FactionAPI.Services.Core.Models.Supporter", null)
                        .WithMany("Appearances")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FactionAPI.Services.Core.Models.Supporter", b =>
                {
                    b.Navigation("Appearances");
                });
#pragma warning restore 612, 618
        }
    }
}
